=== omarnasir/ID2208_HW2/FlightReservationSystemService/src/xmlFiles/flightDataSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.flightreservationcompany.org/flightdataschema.xsd"
	xmlns:tns="http://www.flightreservationcompany.org/flightdataschema.xsd"
	elementFormDefault="qualified">
	<xsd:element name="flightData">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="itinerary" minOccurs="0" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="flightNum" type="xsd:integer" />
							<xsd:element name="depTime" type="xsd:time" />
							<xsd:element name="arrTime" type="xsd:time" />
							<xsd:element name="flightDate" type="xsd:date" />
							<xsd:element name="price" type="xsd:integer" />
							<xsd:element name="tickets" type="xsd:integer" />
						</xsd:sequence>
						<xsd:attribute name="fromCity" type="xsd:string" />
						<xsd:attribute name="toCity" type="xsd:string" />
						<xsd:attribute name="id" type="xsd:integer" />
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== omarnasir/ID2208_HW2/FlightReservationSystemService/src/xmlFiles/flightData.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:flightData xmlns:tns="http://www.flightreservationcompany.org/flightdataschema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.flightreservationcompany.org/flightdataschema.xsd flightDataSchema.xsd ">
  <tns:itinerary fromCity="Stockholm" id="0" toCity="London">
  <tns:flightNum>111</tns:flightNum>
    <tns:depTime>12:00:00</tns:depTime>
    <tns:arrTime>15:00:00</tns:arrTime>
    <tns:flightDate>2017-01-01</tns:flightDate>
    <tns:price>500</tns:price>
    <tns:tickets>10</tns:tickets>
  </tns:itinerary>
  <tns:itinerary fromCity="London" id="1" toCity="Paris">
    <tns:flightNum>112</tns:flightNum>
    <tns:depTime>12:00:00</tns:depTime>
    <tns:arrTime>15:00:00</tns:arrTime>
    <tns:flightDate>2017-01-02</tns:flightDate>
    <tns:price>400</tns:price>
    <tns:tickets>5</tns:tickets>
  </tns:itinerary>
  <tns:itinerary fromCity="Stockholm" id="2" toCity="Berlin">
    <tns:flightNum>113</tns:flightNum>
    <tns:depTime>12:00:00</tns:depTime>
    <tns:arrTime>15:00:00</tns:arrTime>
    <tns:flightDate>2017-01-01</tns:flightDate>
    <tns:price>700</tns:price>
    <tns:tickets>0</tns:tickets>
  </tns:itinerary>
</tns:flightData>
